# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/TIBCOSoftware/flogo-contrib"
  branch = "master"

[[constraint]]
  name = "github.com/TIBCOSoftware/flogo-lib"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/debovema/flogo-opentracing-listener"
